name: central_heating_control
description: "Central Heating Control by Heethings"
publish_to: 'none'
version: 1.0.10+1010

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  dart_periphery: ^0.9.5
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_guid: ^0.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons: 

flutter_native_splash:
  color: "#0087DE"
  image: "assets/images/app_icon_2.png"
  color_dark: "#0087DE"
  image_dark: "assets/images/app_icon_2.png"
  android_12:
    image: "assets/images/app_icon_2.png"
    color: "#0087DE"
    icon_background_color: "#0087DE"
  fullscreen: true  

flutter:
  uses-material-design: true

  assets:
    - assets/images/


# dart run flutter_native_splash:create --path=pubspec.yaml    