name: central_heating_control
description: "Central Heating Control by Heethings"
publish_to: 'none'
version: 1.2.0-alpha.4+1200

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  dart_periphery: ^0.9.6
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_guid: ^0.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  rpi_gpio: ^0.9.1
  sqflite_common_ffi: ^2.3.3
  window_manager: ^0.3.8
  on_screen_keyboard_tr:
    path: modules/on_screen_keyboard_tr/
  screen_saver:
    path: modules/screen_saver/
  network_info_plus: ^5.0.3
  flutter_libserialport: ^0.4.0
  google_fonts: ^6.2.1
  process_run: ^1.0.0+1
  flutter_smart_dialog: ^4.9.7+9
  flutter_markdown: ^0.7.3+1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons: 
  android: false
  ios: false
  image_path: "assets/images/app_icon.png"
  web:
    generate: false
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#0087DE"
  image: "assets/images/app_icon_2.png"
  color_dark: "#0087DE"
  image_dark: "assets/images/app_icon_2.png"
  android_12:
    image: "assets/images/app_icon_2.png"
    color: "#0087DE"
    icon_background_color: "#0087DE"
  fullscreen: true  

flutter:
  uses-material-design: true

  assets:
    - assets/images/


# sudo apt-get -y install libsqlite3-0 libsqlite3-dev

# dart run flutter_native_splash:create --path=pubspec.yaml    
# dart run flutter_launcher_icons:main -f pubspec.yaml


# rsync -avz ~/Development/FlutterProjects/heethings/CentralHeatingControl/CHC pi@192.168.1.248:~/Development

# export PATH="$PATH:/snap/bin"
