const Map<String, String> enUS = {
  'appName': 'CCU1994',
  'Sunday':'Sunday',
  'Monday':'Monday',
  'Tuesday':'Tuesday',
  'Wednesday':'Wednesday',
  'Thursday':'Thursday',
  'Friday':'Friday',
  'Saturday':'Saturday',
  'January':'January',
  'February':'February',
  'March':'March',
  'April':'April',
  'May':'May',
  'June':'June',
  'July':'July',
  'August':'August',
  'September':'September',
  'October':'October',
  'November':'November',
  'December':'December',
  'cancel': 'Cancel',
  'Next': 'Next',
  'Previous': 'Previous',
  'Retry': 'Retry',
  'Error': 'Error',
  'An Unexpected Error Occurred': 'An Unexpected Error Occurred',
  'Setup ': 'Setup ',
  'Initial Setup': 'Initial Setup',
  'Language': 'Language',
  'Choose your language': 'Choose your language',
  'Timezone': 'Timezone',
  'Date Format': 'Date Format',
  'Theme': 'Theme',
  'Terms of Use': 'Terms of Use',
  'Privacy Policy': 'Privacy Policy',
  'Register Device': 'Register Device',
  'Sign In': 'Sign In',
  'Sign in': 'Sign in',
  'Signing in': 'Signing in',
  'Incorrect credentials': 'Incorrect credentials',
  'Activation': 'Activation',
  'Subscription Status': 'Subscription Status',
  'Tech Support': 'Tech Support',
  'Admin User': 'Admin User',
  'Confirm your timezone': 'Confirm your timezone',
  'Date/Time': 'Date/Time',
  'Choose a Date Time Format': 'Choose a Date Time Format',
  'Time Format': 'Time Format',
  'Preview': 'Preview',
  'I agree to the terms of use': 'I agree to the terms of use',
  'I agree to the privacy policy': 'I agree to the privacy policy',
  'Registering Device...': 'Registering Device...',
  'Sign in with your Heethings account': 'Sign in with your Heethings account',
  'Email': 'Email',
  'Password': 'Password',
  'Forgot Password': 'Forgot Password',
  'Create an Account': 'Create an Account',
  'Activating...': 'Activating...',
  'Requesting Subscription Status...': 'Requesting Subscription Status...',
  'Please create a user for Tech Support':
      'Please create a user for Tech Support',
  'Save': 'Save',
  'User creation failed': 'User creation failed',
  'Full Name': 'Full Name',
  'PIN Code': 'PIN Code',
  'This user can access to all sections including advanced settings':
      'This user can access to all sections including advanced settings',
  'Please create an admin user': 'Please create an admin user',
  'This user has the `Manager Role` and has access to the following features:\n- Control and manage Zones, heaters, sensors\n- Create, edit, run Functions\n- Manage Users\n- Change device settings like language, timezone, date time, theme.\n':
      'This user has the `Manager Role` and has access to the following features:\n- Control and manage Zones, heaters, sensors\n- Create, edit, run Functions\n- Manage Users\n- Change device settings like language, timezone, date time, theme.\n',
  'Select Theme': 'Select Theme',
  'Pick a theme': 'Pick a theme',
  'Sample': 'Sample',
  'Default': 'Default',
  'Nature': 'Nature',
  'Warmy': 'Warmy',
  'Crimson': 'Crimson',
};
