const Map<String, String> trTR = {
  'appName': 'CCU1994',
  'cancel': 'İptal',
  'Next': 'Sonraki',
  'Previous': 'Önceki',
  'Retry': 'Tekrar Dene',
  'Error': 'Hata',
  'An Unexpected Error Occurred': 'Beklenmedik bir hata oluştu',
  'Setup ': 'Kurulum ',
  'Initial Setup': 'İlk Kurulum',
  'Language': 'Lisan',
  'Choose your language': 'Görüntüleme dilinizi seçin',
  'Timezone': 'Zaman Dilimi',
  'Date Format': 'Tarih Biçimi',
  'Theme': 'Tema',
  'Terms of Use': 'Kullanım Şartları',
  'Privacy Policy': 'Gizlilik Politikası',
  'Register Device': 'Cihaz Kaydı',
  'Sign In': 'Oturum Açın',
  'Sign in': 'Giriş Yap',
  'Signing in': 'Giriş Yapılıyor',
  'Incorrect credentials': 'Hatalı kimlik bilgileri',
  'Activation': 'Aktivasyon',
  'Subscription Status': 'Abonelik Durumu',
  'Tech Support': 'Teknik Destek',
  'Admin User': 'Admin Kullanıcı',
  'Confirm your timezone': 'Zaman Diliminizi Seçin',
  'Date/Time': 'Tarih/Saat',
  'Choose a Date Time Format': 'Tarih Saat Formatını Seçin',
  'Time Format': 'Saat Formatı',
  'Preview': 'Önizleme',
  'I agree to the terms of use': 'Kullanım sartlarını kabul ediyorum',
  'I agree to the privacy policy': 'Gizlilik Politikasını kabul ediyorum',
  'Registering Device...': 'Cihaz kaydı yapılıyor...',
  'Sign in with your Heethings account': 'Heethings hesabınız ile oturum açın',
  'Email': 'E-posta',
  'Password': 'Şifre',
  'Forgot Password': 'Şifremi Unuttum',
  'Create an Account': 'Hesap Oluştur',
  'Activating...': 'Aktivasyon yapılıyor...',
  'Requesting Subscription Status...': 'Abonelik Sorgulanıyor',
  'Please create a user for Tech Support':
      'Bir teknik destek kullanıcısı yaratın',
  'Save': 'Kaydet',
  'User creation failed': 'Kullanıcı eklenemedi',
  'Full Name': 'İsim Soyisim',
  'PIN Code': 'PIN Kodu',
  'This user can access to all sections including advanced settings':
      'Bu kullanıcı gelişmiş ayarlar dahil tüm bölümlerde yetkilidir.',
  'Please create an admin user': 'Lütfen bir yönetici hesabı oluşturun',
  'This user has the `Manager Role` and has access to the following features:\n- Control and manage Zones, heaters, sensors\n- Create, edit, run Functions\n- Manage Users\n- Change device settings like language, timezone, date time, theme.\n':
      'Bu kullanıcı yönetici rolü ile aşağıdaki özelliklerde yetki sahibidir\n- Bölge, ısıtıcı, sensör kontolü ve yönetimi\n- Fonksiyon yaratma, düzenleme ve çalıştırma\n- Kullanıcı yönetimi\n- Cihaz ayarları ve yönetimi (lisan, zaman dilimi, tarih formatı, tema gibi)',
'Select Theme':'Tema Seçin',
'Pick a theme':'Bir Tema Seçin',
'Sample':'Örnek',

};
